name: Windows Forms Release

on:
  push:
    tags:
        - "classic-v*.*.*"
  workflow_dispatch:

env:
  project_path: ./app/gratch.classic/gratch.classic.csproj 
  artifacts_path: ./artifacts/
  runtime: win-x64

jobs:
  publish:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Restore
          run: dotnet restore $project_path -r win-x64
        - name: Build
          run: dotnet build --no-restore ${{ env.project_path }} -r ${{ env.runtime }} -c Release
        - name: Publish
          run: dotnet publish ${{ env.project_path }} -o ${{ env.artifacts_path }} --no-build -r ${{ env.runtime }} --no-self-contained
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files:
                ${{ env.artifacts_path }}/*.exe
            draft: true